# בסיס לכתובת
@base = http://localhost:3000

### Health
GET {{base}}/health


### Create patient (קחי את ה-_id מהתגובה לשימוש ב-@id למטה)
POST {{base}}/patients
Content-Type: application/json

{
  "name": "Yael",
  "age": 20
}


### List patients – בסיסי
GET {{base}}/patients


### List with pagination (page 1, limit 5)
GET {{base}}/patients?page=1&limit=5


### List with search by name (case-insensitive)
GET {{base}}/patients?q=ya


### List with age filter (18–40)
GET {{base}}/patients?minAge=18&maxAge=40


### List with sorting by name ascending
GET {{base}}/patients?sortBy=name&sortDir=asc


### List – שילוב: עמודים + חיפוש + מיון
GET {{base}}/patients?page=2&limit=3&q=ya&sortBy=createdAt&sortDir=desc



 ### Get single patient by id
@oneId = 68ca978f3c9039c4198c6b57



GET {{base}}/patients/{{oneId}}


### ----- פעולות לפי מזהה -----
# עדכני כאן את ה-id לאחר יצירה/מתוך Compass
@id = 68ca978f3c9039c4198c6b57


### Update patient
PUT {{base}}/patients/{{id}}
Content-Type: application/json

{
  "name": "Yael Updated",
  "age": 28
}


### Delete patient
DELETE {{base}}/patients/{{id}}
